# Generated by Django 2.0.2 on 2020-01-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_pictures_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculties',
            name='url_Instagram',
        ),
        migrations.RemoveField(
            model_name='faculties',
            name='url_Twitter',
        ),
    ]
