# Generated by Django 2.0.2 on 2020-01-10 06:57

from django.db import migrations, models
import school_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_auto_20200109_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='image',
            field=models.ImageField(upload_to=school_app.models.content_file_name1),
        ),
    ]
