# Generated by Django 2.0.2 on 2020-01-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_auto_20200110_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculties',
            name='url_Instagram',
        ),
        migrations.RemoveField(
            model_name='faculties',
            name='url_Twitter',
        ),
    ]
